export const actionType = {
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    LOGIN: 'LOGIN',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGOUT: 'LOGOUT',
    GET_POST: 'GET_POST',
    ADD_POST: 'ADD_POST',
    DELETE_POST: 'DELETE_POST',
    REQUEST_SIGNUP: 'REQUEST_SIGNUP',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
  }